# Generated by Django 4.0.1 on 2022-01-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KdCollectorAscent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queueid', models.CharField(max_length=32)),
                ('rank_id', models.IntegerField()),
                ('red_team_econ', models.CharField(max_length=32)),
                ('blue_team_econ', models.CharField(max_length=32)),
                ('attacker_team', models.CharField(max_length=32)),
                ('victim_team', models.CharField(max_length=32)),
                ('attacker_location_x', models.IntegerField()),
                ('attacker_location_y', models.IntegerField()),
                ('victim_location_x', models.IntegerField()),
                ('victim_location_y', models.IntegerField()),
                ('plant_status', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'kd_collector_ASCENT',
            },
        ),
        migrations.CreateModel(
            name='KdCollectorBind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queueid', models.CharField(max_length=32)),
                ('rank_id', models.IntegerField()),
                ('red_team_econ', models.CharField(max_length=32)),
                ('blue_team_econ', models.CharField(max_length=32)),
                ('attacker_team', models.CharField(max_length=32)),
                ('victim_team', models.CharField(max_length=32)),
                ('attacker_location_x', models.IntegerField()),
                ('attacker_location_y', models.IntegerField()),
                ('victim_location_x', models.IntegerField()),
                ('victim_location_y', models.IntegerField()),
                ('plant_status', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'kd_collector_BIND',
            },
        ),
        migrations.CreateModel(
            name='KdCollectorBreeze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queueid', models.CharField(max_length=32)),
                ('rank_id', models.IntegerField()),
                ('red_team_econ', models.CharField(max_length=32)),
                ('blue_team_econ', models.CharField(max_length=32)),
                ('attacker_team', models.CharField(max_length=32)),
                ('victim_team', models.CharField(max_length=32)),
                ('attacker_location_x', models.IntegerField()),
                ('attacker_location_y', models.IntegerField()),
                ('victim_location_x', models.IntegerField()),
                ('victim_location_y', models.IntegerField()),
                ('plant_status', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'kd_collector_BREEZE',
            },
        ),
        migrations.CreateModel(
            name='KdCollectorFracture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queueid', models.CharField(max_length=32)),
                ('rank_id', models.IntegerField()),
                ('red_team_econ', models.CharField(max_length=32)),
                ('blue_team_econ', models.CharField(max_length=32)),
                ('attacker_team', models.CharField(max_length=32)),
                ('victim_team', models.CharField(max_length=32)),
                ('attacker_location_x', models.IntegerField()),
                ('attacker_location_y', models.IntegerField()),
                ('victim_location_x', models.IntegerField()),
                ('victim_location_y', models.IntegerField()),
                ('plant_status', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'kd_collector_FRACTURE',
            },
        ),
        migrations.CreateModel(
            name='KdCollectorHaven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queueid', models.CharField(max_length=32)),
                ('rank_id', models.IntegerField()),
                ('red_team_econ', models.CharField(max_length=32)),
                ('blue_team_econ', models.CharField(max_length=32)),
                ('attacker_team', models.CharField(max_length=32)),
                ('victim_team', models.CharField(max_length=32)),
                ('attacker_location_x', models.IntegerField()),
                ('attacker_location_y', models.IntegerField()),
                ('victim_location_x', models.IntegerField()),
                ('victim_location_y', models.IntegerField()),
                ('plant_status', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'kd_collector_HAVEN',
            },
        ),
        migrations.CreateModel(
            name='KdCollectorIcebox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queueid', models.CharField(max_length=32)),
                ('rank_id', models.IntegerField()),
                ('red_team_econ', models.CharField(max_length=32)),
                ('blue_team_econ', models.CharField(max_length=32)),
                ('attacker_team', models.CharField(max_length=32)),
                ('victim_team', models.CharField(max_length=32)),
                ('attacker_location_x', models.IntegerField()),
                ('attacker_location_y', models.IntegerField()),
                ('victim_location_x', models.IntegerField()),
                ('victim_location_y', models.IntegerField()),
                ('plant_status', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'kd_collector_ICEBOX',
            },
        ),
        migrations.CreateModel(
            name='KdCollectorSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queueid', models.CharField(max_length=32)),
                ('rank_id', models.IntegerField()),
                ('red_team_econ', models.CharField(max_length=32)),
                ('blue_team_econ', models.CharField(max_length=32)),
                ('attacker_team', models.CharField(max_length=32)),
                ('victim_team', models.CharField(max_length=32)),
                ('attacker_location_x', models.IntegerField()),
                ('attacker_location_y', models.IntegerField()),
                ('victim_location_x', models.IntegerField()),
                ('victim_location_y', models.IntegerField()),
                ('plant_status', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'kd_collector_SPLIT',
            },
        ),
        migrations.CreateModel(
            name='PlantLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queueid', models.CharField(max_length=32)),
                ('mapid', models.CharField(max_length=32)),
                ('rank_id', models.IntegerField()),
                ('red_team_econ', models.CharField(max_length=32)),
                ('blue_team_econ', models.CharField(max_length=32)),
                ('location_x', models.IntegerField()),
                ('location_y', models.IntegerField()),
            ],
            options={
                'db_table': 'PLANT_LOCATIONS',
            },
        ),
    ]
